// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtb_core.h for the primary calling header

#ifndef VERILATED_VTB_CORE___024ROOT_H_
#define VERILATED_VTB_CORE___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"

class Vtb_core__Syms;

class Vtb_core___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ tb_core__DOT__tb_data_clk;
        CData/*0:0*/ tb_core__DOT__tb_rst;
        CData/*1:0*/ tb_core__DOT__tb_din;
        CData/*0:0*/ tb_core__DOT__tb_en_dout;
        CData/*0:0*/ tb_core__DOT__parity_gen;
        CData/*0:0*/ tb_core__DOT____Vlvbound_hd0ac00da__0;
        CData/*0:0*/ tb_core__DOT__dut__DOT__cts_UART;
        CData/*1:0*/ tb_core__DOT__dut__DOT__tx_1553;
        CData/*0:0*/ tb_core__DOT__dut__DOT__m1553_decoder_valid;
        CData/*7:0*/ tb_core__DOT__dut__DOT__m1553_decoder_user;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mfifo_decoder_valid;
        CData/*7:0*/ tb_core__DOT__dut__DOT__mfifo_decoder_user;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mfifo_decoder_ready;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mstring_encoder_valid;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mstring_to_char_ready;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mout_char_fifo_ready;
        CData/*7:0*/ tb_core__DOT__dut__DOT__muart_char_data;
        CData/*0:0*/ tb_core__DOT__dut__DOT__muart_char_valid;
        CData/*0:0*/ tb_core__DOT__dut__DOT__muart_char_ready;
        CData/*0:0*/ tb_core__DOT__dut__DOT__min_char_fifo_ready;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mchar_to_string_ready;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mstring_decoder_valid;
        CData/*7:0*/ tb_core__DOT__dut__DOT__mstring_decoder_user;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mfifo_encoder_valid;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mfifo_encoder_ready;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__parity_bit;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__delay_bit;
        CData/*4:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__state;
        CData/*7:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__cmd;
        CData/*1:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__p_diff;
        CData/*5:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__skip_counter;
        CData/*7:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__pause_counter;
        CData/*5:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__trans_counter;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__s_rd_valid;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__s_wr_full;
        CData/*1:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_rd_valid;
        CData/*1:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_rd_empty;
        CData/*1:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_wr_ack;
        CData/*1:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_wr_full;
        CData/*1:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__read_state;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__tail;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_tail;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_gr_head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_gr_tail;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__next_head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__next_tail;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__rd_head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__wr_tail;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__rd_ctrl_mem;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_rd_empty;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_rd_rstn;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_wr_rstn;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_data_count;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_fwft_count;
        CData/*7:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_control__DOT__s_tlast_count;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_control__DOT__r_mclk_s_axis_tlast;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_control__DOT__rr_mclk_s_axis_tlast;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_control__DOT__r_mclk_w_full;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_control__DOT__rr_mclk_w_full;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_control__DOT__r_rd_valid;
        CData/*0:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_control__DOT__s_tlast_full;
        CData/*0:0*/ tb_core__DOT__dut__DOT__string_encoder__DOT__m_axis_tlast;
    };
    struct {
        CData/*0:0*/ tb_core__DOT__dut__DOT__string_encoder__DOT__p_m_axis_tready;
        CData/*0:0*/ tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_valid;
        CData/*7:0*/ tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_m_axis_tdata;
        CData/*5:0*/ tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__counter;
        CData/*5:0*/ tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__index;
        CData/*0:0*/ tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__p_m_axis_tready;
        CData/*7:0*/ tb_core__DOT__dut__DOT__string_to_char__DOT____Vlvbound_h19ee943e__0;
        CData/*2:0*/ tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__index;
        CData/*2:0*/ tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__index_shift;
        CData/*2:0*/ tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__index_check;
        CData/*3:0*/ tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_valid_buffer;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_hold_rx;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_baud_gen_tx__DOT__r_uart_ena;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_baud_gen_rx__DOT__r_uart_ena;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__parity_bit;
        CData/*2:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__state;
        CData/*7:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__data;
        CData/*3:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__trans_counter;
        CData/*3:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__prev_trans_counter;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__trans_fin;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__reg_txd;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__parity_bit;
        CData/*2:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__state;
        CData/*1:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__uart_state;
        CData/*7:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__data;
        CData/*3:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__trans_counter;
        CData/*3:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__prev_trans_counter;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__p_rxd;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__trans_fin;
        CData/*0:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT____Vlvbound_h650e6985__0;
        CData/*2:0*/ tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__index;
        CData/*2:0*/ tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__index_shift;
        CData/*2:0*/ tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__index_check;
        CData/*3:0*/ tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_valid_buffer;
        CData/*0:0*/ tb_core__DOT__dut__DOT__char_to_string__DOT__reg_data_valid;
        CData/*5:0*/ tb_core__DOT__dut__DOT__char_to_string__DOT__counter;
        CData/*5:0*/ tb_core__DOT__dut__DOT__char_to_string__DOT__index;
        CData/*0:0*/ tb_core__DOT__dut__DOT__char_to_string__DOT__p_m_axis_tready;
        CData/*7:0*/ tb_core__DOT__dut__DOT__char_to_string__DOT____Vlvbound_h203aa844__0;
        CData/*0:0*/ tb_core__DOT__dut__DOT__string_decoder__DOT__s_axis_tlast;
        CData/*0:0*/ tb_core__DOT__dut__DOT__string_decoder__DOT__p_m_axis_tready;
        CData/*0:0*/ tb_core__DOT__dut__DOT__string_decoder__DOT__force_s_axis_tready;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__s_rd_valid;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__s_wr_full;
        CData/*1:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_rd_valid;
        CData/*1:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_rd_empty;
        CData/*1:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_wr_ack;
        CData/*1:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_wr_full;
        CData/*1:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__read_state;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__tail;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_tail;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_gr_head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_gr_tail;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__next_head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__next_tail;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__rd_head;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__wr_tail;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__rd_ctrl_mem;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_rd_empty;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_rd_rstn;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_wr_rstn;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_data_count;
    };
    struct {
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_fwft_count;
        CData/*7:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_control__DOT__s_tlast_count;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_control__DOT__r_mclk_s_axis_tlast;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_control__DOT__rr_mclk_s_axis_tlast;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_control__DOT__r_mclk_w_full;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_control__DOT__rr_mclk_w_full;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_control__DOT__r_rd_valid;
        CData/*0:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_control__DOT__s_tlast_full;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__parity_bit;
        CData/*2:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__state;
        CData/*7:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__cmd;
        CData/*5:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__skip_counter;
        CData/*7:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__pause_counter;
        CData/*5:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__trans_counter;
        CData/*5:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__prev_trans_counter;
        CData/*0:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT____Vlvbound_h6a4c94f2__0;
        CData/*0:0*/ __Vdlyvval__tb_core__DOT__tb_data_clk__v0;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__tb_data_clk__v0;
        CData/*0:0*/ __Vdly__tb_core__DOT__parity_gen;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_decoder__DOT__pause_counter;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__m1553_decoder_valid;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__m1553_decoder_user;
        CData/*4:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_decoder__DOT__state;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_decoder__DOT__parity_bit;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_decoder__DOT__delay_bit;
        CData/*5:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_decoder__DOT__skip_counter;
        CData/*5:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_decoder__DOT__trans_counter;
        CData/*1:0*/ __Vdly__tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__read_state;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__tail;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_tail;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_head;
        CData/*7:0*/ __Vdlyvdim0__tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__memory__DOT__fifo_ram__v0;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__memory__DOT__fifo_ram__v0;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__string_encoder__DOT__p_m_axis_tready;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v0;
        CData/*5:0*/ __Vdly__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__counter;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__p_m_axis_tready;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v1;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v21;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v21;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v22;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v22;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v23;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v23;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v24;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v24;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v25;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v25;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v26;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v26;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v27;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v27;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v28;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v28;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v29;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v29;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v30;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v30;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v31;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v31;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v32;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v32;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v33;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v33;
    };
    struct {
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v34;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v34;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v35;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v35;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v36;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v36;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v37;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v37;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v38;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v38;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v39;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v39;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v40;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v40;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v41;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer__v41;
        CData/*3:0*/ __Vdly__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_valid_buffer;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v0;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v4;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v4;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v5;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v5;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v6;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v6;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v7;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v7;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v8;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v8;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v9;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v9;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v10;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer__v10;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__data;
        CData/*2:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__state;
        CData/*3:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__trans_counter;
        CData/*3:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__prev_trans_counter;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__muart_char_data;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__muart_char_valid;
        CData/*2:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__state;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__data;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__parity_bit;
        CData/*1:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__uart_state;
        CData/*3:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__trans_counter;
        CData/*3:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__prev_trans_counter;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_hold_rx;
        CData/*3:0*/ __Vdly__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_valid_buffer;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v0;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v4;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v4;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v5;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v5;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v6;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v6;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v7;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v7;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v8;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v8;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v9;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v9;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v10;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer__v10;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__char_to_string__DOT__reg_data_buffer__v0;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__char_to_string__DOT__reg_data_valid;
        CData/*5:0*/ __Vdly__tb_core__DOT__dut__DOT__char_to_string__DOT__counter;
    };
    struct {
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__char_to_string__DOT__p_m_axis_tready;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__char_to_string__DOT__reg_data_buffer__v1;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__char_to_string__DOT__reg_data_buffer__v21;
        CData/*4:0*/ __Vdlyvdim0__tb_core__DOT__dut__DOT__char_to_string__DOT__reg_data_buffer__v42;
        CData/*7:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__char_to_string__DOT__reg_data_buffer__v42;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__char_to_string__DOT__reg_data_buffer__v42;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__string_decoder__DOT__p_m_axis_tready;
        CData/*1:0*/ __Vdly__tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__read_state;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__tail;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_tail;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__control__DOT__r_head;
        CData/*7:0*/ __Vdlyvdim0__tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__memory__DOT__fifo_ram__v0;
        CData/*0:0*/ __Vdlyvset__tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__memory__DOT__fifo_ram__v0;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_encoder__DOT__pause_counter;
        CData/*7:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_encoder__DOT__cmd;
        CData/*2:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_encoder__DOT__state;
        CData/*0:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_encoder__DOT__parity_bit;
        CData/*5:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_encoder__DOT__trans_counter;
        CData/*5:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_encoder__DOT__skip_counter;
        CData/*0:0*/ __Vtrigrprev__TOP__tb_core__DOT__tb_data_clk;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ tb_core__DOT__data;
        SData/*15:0*/ tb_core__DOT__dut__DOT__m1553_decoder_data;
        SData/*15:0*/ tb_core__DOT__dut__DOT__mfifo_decoder_data;
        SData/*15:0*/ tb_core__DOT__dut__DOT__mstring_decoder_data;
        SData/*15:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__data;
        SData/*9:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__reg_data;
        SData/*9:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_rx__DOT__reg_data;
        SData/*15:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__data;
        SData/*15:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__r_data;
        SData/*15:0*/ __Vdly__tb_core__DOT__data;
        SData/*15:0*/ __Vdly__tb_core__DOT__dut__DOT__m1553_decoder_data;
        SData/*15:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_decoder__DOT__data;
        SData/*9:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_tx__DOT__reg_data;
        SData/*15:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_encoder__DOT__data;
        SData/*15:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_encoder__DOT__r_data;
        VlWide<25>/*799:0*/ tb_core__DOT__data_expand;
        VlWide<32>/*999:0*/ tb_core__DOT__reg_data;
        IData/*31:0*/ tb_core__DOT__xor_index;
        IData/*31:0*/ tb_core__DOT__cycle_index;
        IData/*31:0*/ tb_core__DOT__pos_counter;
        IData/*31:0*/ tb_core__DOT__delay_counter;
        VlWide<6>/*167:0*/ tb_core__DOT__dut__DOT__mchar_to_string_data;
        IData/*31:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__bit_slice_index;
        IData/*31:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__s_rd_data;
        IData/*31:0*/ tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__index;
        IData/*20:0*/ tb_core__DOT__dut__DOT__string_encoder__DOT__m_axis_tkeep;
        VlWide<6>/*167:0*/ tb_core__DOT__dut__DOT__string_encoder__DOT__r_m_axis_tdata;
        IData/*26:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_baud_gen_tx__DOT__counter;
        IData/*26:0*/ tb_core__DOT__dut__DOT__axis_uart__DOT__uart_baud_gen_rx__DOT__counter;
        IData/*20:0*/ tb_core__DOT__dut__DOT__string_decoder__DOT__s_axis_tkeep;
        IData/*31:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__s_rd_data;
        IData/*31:0*/ tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__index;
        IData/*31:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__xor_index;
        IData/*31:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__cycle_index;
        IData/*31:0*/ __Vdly__tb_core__DOT__pos_counter;
        IData/*31:0*/ __Vdly__tb_core__DOT__delay_counter;
        VlWide<25>/*799:0*/ __Vdly__tb_core__DOT__data_expand;
        VlWide<32>/*999:0*/ __Vdly__tb_core__DOT__reg_data;
        IData/*31:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__memory__DOT__fifo_ram__v0;
        IData/*26:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_baud_gen_tx__DOT__counter;
        IData/*26:0*/ __Vdly__tb_core__DOT__dut__DOT__axis_uart__DOT__uart_baud_gen_rx__DOT__counter;
        IData/*31:0*/ __Vdlyvval__tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__memory__DOT__fifo_ram__v0;
        IData/*31:0*/ __VstlIterCount;
    };
    struct {
        IData/*31:0*/ __VactIterCount;
        QData/*39:0*/ tb_core__DOT__dut__DOT__mil1553_decoder__DOT__reg_data;
        QData/*39:0*/ tb_core__DOT__dut__DOT__mil1553_encoder__DOT__reg_data;
        QData/*39:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_decoder__DOT__reg_data;
        QData/*39:0*/ __Vdly__tb_core__DOT__dut__DOT__mil1553_encoder__DOT__reg_data;
        VlUnpacked<IData/*31:0*/, 2> tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_rd_data;
        VlUnpacked<IData/*31:0*/, 2> tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_wr_data;
        VlUnpacked<CData/*0:0*/, 2> tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_data_count;
        VlUnpacked<IData/*31:0*/, 256> tb_core__DOT__dut__DOT__decoder_fifo__DOT__axis_fifo__DOT__memory__DOT__fifo_ram;
        VlUnpacked<CData/*7:0*/, 21> tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__reg_data_buffer;
        VlUnpacked<CData/*7:0*/, 21> tb_core__DOT__dut__DOT__string_to_char__DOT__genblk1__DOT__split_s_axis_tdata;
        VlUnpacked<CData/*7:0*/, 4> tb_core__DOT__dut__DOT__outgoing_char_fifo__DOT__reg_data_buffer;
        VlUnpacked<CData/*7:0*/, 4> tb_core__DOT__dut__DOT__incomming_char_fifo__DOT__reg_data_buffer;
        VlUnpacked<CData/*7:0*/, 21> tb_core__DOT__dut__DOT__char_to_string__DOT__reg_data_buffer;
        VlUnpacked<IData/*31:0*/, 2> tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_rd_data;
        VlUnpacked<IData/*31:0*/, 2> tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_wr_data;
        VlUnpacked<CData/*0:0*/, 2> tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__pipe__DOT__reg_data_count;
        VlUnpacked<IData/*31:0*/, 256> tb_core__DOT__dut__DOT__encoder_fifo__DOT__axis_fifo__DOT__memory__DOT__fifo_ram;
        VlUnpacked<CData/*0:0*/, 5> __Vm_traceActivity;
    };
    VlDelayScheduler __VdlySched;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtb_core__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vtb_core___024root(Vtb_core__Syms* symsp, const char* v__name);
    ~Vtb_core___024root();
    VL_UNCOPYABLE(Vtb_core___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
